plugins {
    id 'com.android.application'
}

android {
    namespace 'pk.azankhan.vidloom'
    compileSdk 36

    defaultConfig {
        applicationId 'pk.azankhan.vidloom'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '1.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core-ktx:1.17.0'
}
